/*
 * File: app/view/BasePanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.BasePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.basePanel',

    requires: [
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.Text',
        'Ext.toolbar.Spacer',
        'Ext.resizer.Splitter'
    ],

    PanelNo: '1',
    itemId: 'basePanel',
    padding: '',
    ui: 'addredui',
    iconCls: 'yig-base-s-w',
    title: 'BasePanel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'mainCnt',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            componentCls: 'middle-menu',
                            height: 40,
                            itemId: 'topMainCnt',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    width:125,
                                    itemId: 'topHelpCnt',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    itemId: 'topBtnCnt',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'leftPanelUpdateBtn',
                                            margin: '0 2 0 0',
                                            ui: 'update-btn-ui-small',
                                            iconCls: 'yig-update-s-w',
                                            text: 'Update'
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'leftPanelAddBtn',
                                            margin: '0 2 0 0',
                                            ui: 'add-btn-ui-small',
                                            iconCls: 'yig-add-s-w',
                                            text: 'Add'
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'middleCntSaveBtn',
                                            margin: '0 2 0 0',
                                            ui: 'save-btn-ui-small',
                                            iconCls: 'yig-save-s-w',
                                            text: 'Save'
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'middleCntDeleteBtn',
                                            margin: '0 2 0 0',
                                            ui: 'del-btn-ui-small',
                                            iconCls: 'yig-cancel-s-w',
                                            text: 'Delete'
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'middleCntCsvBtn',
                                            margin: '0 2 0 0',
                                            ui: 'semi-action-small',
                                            iconCls: 'yig-download-s-w',
                                            text: 'Csv',
                                            menu: {
                                                xtype: 'menu',
                                                itemId: 'middleCntCsvMenu',
                                                width: 160,
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        itemId: 'selectedCsvMenu',
                                                        iconCls: 'yig-selected-s-b',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        itemId: 'allCsvMenu',
                                                        iconCls: 'yig-selectall-s-b',
                                                        text: 'Menu Item'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'yig-cmp-print-complete-export',
                                            itemId: 'middleCntPrintBtn',
                                            margin: '0 2 0 0',
                                            ui: 'semi-action-small',
                                            iconCls: 'yig-print-s-w',
                                            text: 'Print',
                                            menu: {
                                                xtype: 'menu',
                                                itemId: 'middleCntPrintMenu',
                                                width: 160,
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        itemId: 'selectedPrintMenu',
                                                        iconCls: 'yig-selected-print-s-b',
                                                        text: 'Menu Item'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        itemId: 'allPrintMenu',
                                                        iconCls: 'yig-selectall-print-s-b',
                                                        text: 'Menu Item'
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'bodyCnt',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    autoRender: true,
                                    itemId: 'leftPanel',
                                    width: 600,
                                    animCollapse: false,
                                    collapseDirection: 'left',
                                    collapsed: false,
                                    collapsedCls: 'collapsed collapsed_cls',
                                    collapsible: true,
                                    title: '',
                                    titleCollapse: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            itemId: 'leftPanelTopCnt',
                                            minHeight: 60,
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'leftPanelSearchFld',
                                                    margin: '0 0 0 5',
                                                    width: 200
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'leftPanelSearchBtn',
                                                    margin: '0 0 0 5',
                                                    iconCls: 'yig-search-s-w',
                                                    text: 'search'
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'leftPanelUpdateBtn',
                                                    margin: '0 5 0 5',
                                                    iconCls: 'yig-update-s-w',
                                                    text: 'update'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'leftPanelGridCnt',
                                            layout: 'fit'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'splitter'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'middleCnt',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 70,
                                            itemId: 'middleDisplayFieldCnt'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'middleGridCnt',
                                            layout: 'fit'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'splitter'
                                },
                                {
                                    xtype: 'panel',
                                    componentCls: 'icon-top-postion',
                                    itemId: 'rightPanel',
                                    width: 400,
                                    autoScroll: true,
                                    layout: 'fit',
                                    animCollapse: false,
                                    collapseDirection: 'right',
                                    collapsed: true,
                                    collapsedCls: 'collapsed collapsed_cls',
                                    collapsible: true,
                                    titleCollapse: true,
                                    items: [
                                        {
                                            xtype: 'container',
                                            itemId: 'rightPanelCnt',
                                            layout: 'fit'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});