/*
 * File: app/view/CommentPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.CommentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.commentPanel',

    requires: [
        'Ext.resizer.Splitter',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea'
    ],

    height: 500,
    itemId: 'commentPanel',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'mainCnt',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'commentCnt',
                            layout: 'fit'
                        },
                        {
                            xtype: 'splitter'
                        },
                        {
                            xtype: 'form',
                            componentCls: 'text-area-comment',
                            height: 80,
                            itemId: 'commentFormPanel',
                            layout: 'fit',
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    itemId: 'ref_record_id',
                                    fieldLabel: 'Label',
                                    name: 'ref_record_id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    itemId: 'table_id',
                                    fieldLabel: 'Label',
                                    name: 'table_id'
                                },
                                {
                                    xtype: 'textareafield',
                                    itemId: 'commentTextarea',
                                    fieldLabel: '',
                                    name: 'comment',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    enableKeyEvents: true,
                                    enterIsSpecial: true
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});