/*
 * File: app/view/CsvImportWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.CsvImportWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.CsvImportWin',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.form.field.FileButton',
        'Ext.form.field.Display',
        'Ext.Img',
        'Ext.form.Label'
    ],

    componentCls: 'incidentwindow',
    frame: true,
    height: 451,
    itemId: 'CsvImportWin',
    width: 640,
    bodyPadding: 10,
    title: 'CSV Import',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    border: 0,
                    itemId: 'btnContainer',
                    margin: '0 0 5 0',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'form',
                            border: 0,
                            itemId: 'csvUploadForm',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: '0 0 5 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'comboCnt'
                                        },
                                        {
                                            xtype: 'filefield',
                                            itemId: 'csvFileUpload',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            name: 'csvFile',
                                            buttonOnly: true,
                                            buttonText: 'File Upload',
                                            buttonConfig: {
                                                xtype: 'filebutton',
                                                itemId: 'csvFileUpload',
                                                text: 'File Upload'
                                            }
                                        },
                                        {
                                            xtype: 'displayfield',
                                            flex: 0,
                                            hidden: true,
                                            itemId: 'step1',
                                            margin: '0 2 0 0',
                                            fieldLabel: '',
                                            value: 'Step 1'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'csvFilePath',
                                            margin: '0 2 0 0',
                                            fieldLabel: '',
                                            name: 'filename',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnCsvCheck',
                                            margin: '0 2 0 0',
                                            iconCls: 'yig-done-s-w',
                                            text: 'Check'
                                        },
                                        {
                                            xtype: 'button',
                                            componentCls: 'delete-btn',
                                            disabled: true,
                                            hidden: true,
                                            itemId: 'btnCsvDelete',
                                            iconCls: 'icons-delete',
                                            text: 'Delete'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            componentCls: 'csvMask-cls',
                            hidden: true,
                            itemId: 'csvMask',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    componentCls: 'csvMask-image-cnt-cls',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 30,
                                            id: 'csvMaskImg',
                                            itemId: 'csvMaskImg',
                                            src: 'images/csv_mask.gif'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            itemId: 'csvMaskLbl',
                                            text: 'Checking CSV'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: 0,
                            itemId: 'logPanel',
                            autoScroll: true,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'additionalInfoContainer',
                    margin: '5 0 0 0',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    width: 110,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'totalCsvRecords',
                                            fieldLabel: 'Total Records',
                                            labelWidth: 75,
                                            value: '0'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            flex: 1,
                                            itemId: 'correctCsvRecords',
                                            fieldLabel: 'Correct Records',
                                            labelWidth: 75,
                                            value: '0'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            margin: '0 0 5 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                pack: 'end'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    hidden: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'newCsvRecords',
                                            fieldLabel: 'New',
                                            labelWidth: 80,
                                            value: '0'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            margin: '0 0 5 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'btnNewCsvInsert',
                                                    iconCls: 'yig-add-s-w',
                                                    text: 'Insert'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            flex: 1,
                                            itemId: 'incorrectCsvRecords',
                                            fieldLabel: 'Incorrect Records',
                                            labelWidth: 75,
                                            value: '0'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: '0 0 5 0',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnErrorCsvDownload',
                                    iconCls: 'yig-download-s-w',
                                    text: 'Download'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'actionBtnContainer',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'btnUpload',
                            iconCls: 'yig-import-s-w',
                            text: 'Update'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'btnCpUpdate',
                            iconCls: 'yig-edit-s-w',
                            text: 'Upload'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancel',
                            margin: '0 0 0 5',
                            iconCls: 'yig-cancel-s-w',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});