/*
 * File: app/view/DatagridTemplateWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.DatagridTemplateWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.datagridTemplateWindow',

    requires: [
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.resizer.Splitter',
        'Ext.grid.plugin.DragDrop',
        'Ext.util.Point'
    ],

    height: 500,
    itemId: 'TemplateFieldWindow',
    width: 620,
    layout: 'fit',
    title: 'Field Templates',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    margin: '0 5 0 5',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            componentCls: 'field-template-help',
                            height: 17,
                            itemId: 'DatagridTemplatesHelpLabel',
                            margin: '',
                            text: ''
                        },
                        {
                            xtype: 'container',
                            height: 35,
                            margin: '-10 0 0 0',
                            width: 566,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    itemId: 'panelNameCombo',
                                    margin: '10 10 0 10 ',
                                    fieldLabel: 'Panel Name',
                                    displayField: 'datagrid_name',
                                    store: 'PanelNameStore',
                                    valueField: 'datagrid_id'
                                },
                                {
                                    xtype: 'container',
                                    height: 35,
                                    width: 606,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'datagridTemplateCombo',
                                            margin: '0 10 0 10',
                                            fieldLabel: 'Template',
                                            maxLength: 20,
                                            displayField: 'template_name',
                                            queryMode: 'local',
                                            store: 'DatagridTemplateStore',
                                            valueField: 'datagrid_template_id'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            itemId: 'isPublicDatagridTemp',
                                            margin: '0 10 0 10',
                                            fieldLabel: '',
                                            boxLabel: 'Is Public'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnUpdateDatagridTemplate',
                                            margin: '0 10 0 0',
                                            ui: 'custom-ui',
                                            iconCls: 'yig-download-s-w',
                                            text: 'Update'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnSaveAsDatagridTemplate',
                                            margin: '5 0 5 0',
                                            ui: 'savebtn-ui',
                                            iconCls: 'yig-save-s-w',
                                            text: 'Save As'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'defaultDatagridPanelGrid',
                                    margin: '5 0 5 0',
                                    width: 220,
                                    autoScroll: true,
                                    title: '',
                                    store: 'DefaultPanelDatagridStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'leftGridFieldName',
                                            minWidth: 150,
                                            dataIndex: 'field_label',
                                            menuDisabled: true,
                                            text: 'FieldName',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'removeAction',
                                            width: 40,
                                            dataIndex: 'string',
                                            menuDisabled: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'splitter'
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'datagridTemplatePanelGrid',
                                    margin: '5 0 5 0',
                                    autoScroll: true,
                                    title: '',
                                    store: 'DatagridTemplatePanelStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'moveColSelected',
                                            width: 20,
                                            dataIndex: 'string',
                                            menuDisabled: true
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'removeColAction',
                                            width: 40,
                                            dataIndex: 'string',
                                            menuDisabled: true,
                                            text: 'removeAction'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'rightGridFieldName',
                                            minWidth: 150,
                                            dataIndex: 'field_label',
                                            menuDisabled: true,
                                            text: 'FieldName',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'columnHideShow',
                                            width: 40,
                                            dataIndex: 'hidden',
                                            menuDisabled: true,
                                            text: 'Hide/Show'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'displayCol',
                                            width: 60,
                                            dataIndex: 'string',
                                            menuDisabled: true,
                                            text: 'displayCol'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'displayOrderColumn',
                                            dataIndex: 'display_order',
                                            menuDisabled: true,
                                            text: 'DisplayOrder'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'columnLock',
                                            width: 40,
                                            dataIndex: 'locked',
                                            menuDisabled: true,
                                            text: 'Lock'
                                        }
                                    ],
                                    viewConfig: {
                                        getRowClass: function(record, rowIndex, rowParams, store) {
                                            if(record.get('locked')===true) {
                                                return 'lock-horizontal-line';
                                            }
                                        },
                                        plugins: [
                                            Ext.create('Ext.grid.plugin.DragDrop', {

                                            })
                                        ]
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnDatagridTemplateCancel',
                                    margin: '5 0 5 10',
                                    ui: 'custom-ui',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnDatagridTemplateApply',
                                    margin: '5 10 5 5',
                                    ui: 'custom-ui',
                                    iconCls: 'yig-done-s-w',
                                    text: 'Apply'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});