/*
 * File: app/view/EcSiteExportPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.EcSiteExportPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ecSiteExportPanel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.plugin.DragDrop',
        'Ext.util.Point',
        'Ext.grid.column.Column',
        'Ext.form.field.Number',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.CellEditing',
        'Ext.resizer.Splitter'
    ],

    PanelNo: '6',
    id: 'EcSiteExportPanel',
    itemId: 'EcSiteExportPanel',
    width: 941,
    autoScroll: true,
    iconCls: 'yig-csv-s-w',
    title: 'EcSiteExportPanel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            width: 900,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'csvBtnContainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'form',
                                            border: false,
                                            height: 37,
                                            itemId: 'EcExportCsv',
                                            margin: '0 0 0 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'filefield',
                                                    flex: 0,
                                                    itemId: 'ImportCsvHeader',
                                                    margin: '0 7 0 7',
                                                    padding: '5 0 0 0 ',
                                                    ui: 'semi-action',
                                                    fieldLabel: 'CSV import',
                                                    labelPad: 0,
                                                    labelWidth: 80,
                                                    name: 'importCsvHeader',
                                                    size: 30,
                                                    buttonMargin: 0,
                                                    buttonOnly: true,
                                                    buttonText: 'Browse'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'radiofield',
                                            hidden: true,
                                            itemId: 'EcCsvType',
                                            width: 50,
                                            fieldLabel: '',
                                            name: 'csvType',
                                            boxLabel: 'EC',
                                            checked: true
                                        },
                                        {
                                            xtype: 'radiofield',
                                            hidden: true,
                                            itemId: 'SquareCsvType',
                                            fieldLabel: '',
                                            name: 'csvType',
                                            boxLabel: 'Square'
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'CsvMasterMappedCombo',
                                            margin: '0 5 0 10',
                                            width: 187,
                                            fieldLabel: '',
                                            displayField: 'report_name',
                                            queryMode: 'local',
                                            store: 'CsvMappedMasterStore',
                                            valueField: 'csv_report_id'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'CsvMasterEditBtn',
                                            ui: 'semi-action',
                                            width: 58,
                                            iconCls: 'yig-edit-s-w',
                                            text: 'Edit'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'EcSiteSaveBtn',
                                            margin: '0 2 0 0',
                                            ui: 'semi-action',
                                            iconCls: 'yig-save-s-w',
                                            text: 'Save'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'EcSiteGrid',
                                    autoScroll: true,
                                    title: '',
                                    store: 'EcSiteStore',
                                    viewConfig: {
                                        enableTextSelection: true,
                                        plugins: [
                                            Ext.create('Ext.grid.plugin.DragDrop', {

                                            })
                                        ]
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'MoveColSelected',
                                            width: 15,
                                            resizable: false,
                                            sortable: false,
                                            menuDisabled: true
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'csv_field_name',
                                            minWidth: 100,
                                            dataIndex: 'csv_field_name',
                                            menuDisabled: true,
                                            text: 'csv_field_name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'DisplayCol',
                                            width: 70,
                                            defaultWidth: 120,
                                            sortable: false,
                                            dataIndex: 'display_order',
                                            menuDisabled: true,
                                            text: 'Display_order'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'mapped_fields',
                                            minWidth: 150,
                                            width: 125,
                                            dataIndex: 'mapped_fields',
                                            menuDisabled: true,
                                            text: 'mapped_fields',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'mapped_table_name',
                                            text: 'mapped_table_name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'mapped_table_id',
                                            width: 80,
                                            dataIndex: 'mapped_table_id',
                                            menuDisabled: true,
                                            text: 'mapped_table_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'field_id',
                                            width: 50,
                                            dataIndex: 'field_id',
                                            menuDisabled: true,
                                            text: 'field_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'csv_mapped_detail_id',
                                            dataIndex: 'csv_mapped_detail_id',
                                            menuDisabled: true,
                                            text: 'csv_mapped_detail_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'is_single_mapped',
                                            dataIndex: 'is_single_mapped',
                                            menuDisabled: true,
                                            text: 'is_single_mapped'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'csv_mapped_master_id',
                                            dataIndex: 'csv_mapped_master_id',
                                            menuDisabled: true,
                                            text: 'csv_mapped_master_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'xtype',
                                            text: 'mapped_field_type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'default_value',
                                            dataIndex: 'default_value',
                                            menuDisabled: true,
                                            text: 'Default Value',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'option_value',
                                            dataIndex: 'option_value',
                                            menuDisabled: true,
                                            text: 'Option Value',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'id_field_table',
                                            dataIndex: 'id_field_table',
                                            menuDisabled: true,
                                            text: 'Id Field Table',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'format_name',
                                            width: 130,
                                            dataIndex: 'format_id',
                                            menuDisabled: true,
                                            text: 'Format Name',
                                            editor: {
                                                xtype: 'combobox',
                                                itemId: 'DataFormatCombo',
                                                editable: false,
                                                displayField: 'format_name',
                                                queryMode: 'local',
                                                store: 'DataFormatStore',
                                                valueField: 'format_id'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'max_length',
                                            width: 60,
                                            dataIndex: 'max_length',
                                            menuDisabled: true,
                                            text: 'max_length',
                                            editor: {
                                                xtype: 'numberfield',
                                                hideTrigger: true,
                                                repeatTriggerClick: false,
                                                keyNavEnabled: false,
                                                mouseWheelEnabled: false,
                                                spinDownEnabled: false,
                                                spinUpEnabled: false,
                                                allowDecimals: false
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'removeAction',
                                            width: 40,
                                            menuDisabled: true,
                                            text: 'Action '
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                                        mode: 'SINGLE'
                                    }),
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                        })
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'splitter'
                        },
                        {
                            xtype: 'container',
                            flex: 0.5,
                            width: 350,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    height: 37,
                                    margin: '0 0 0 0',
                                    padding: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'end',
                                        padding: '10 -8 0 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'EcSiteCancelBtn',
                                            margin: '',
                                            iconCls: 'cancel-icon',
                                            text: 'Cancel'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 0.5,
                                    itemId: 'winstonGrid',
                                    autoScroll: true,
                                    title: '',
                                    store: 'WinstonStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'selectionColumn',
                                            minWidth: 50,
                                            width: 50,
                                            menuDisabled: true,
                                            text: 'Operation'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 100,
                                            dataIndex: 'field_label',
                                            menuDisabled: true,
                                            text: 'field_label',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 50,
                                            dataIndex: 'table_id',
                                            menuDisabled: true,
                                            text: 'table_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 60,
                                            dataIndex: 'table_field_id',
                                            menuDisabled: true,
                                            text: 'table_field_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'xtype',
                                            menuDisabled: true,
                                            text: 'field_type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'ismapped',
                                            minWidth: 50,
                                            width: 40,
                                            menuDisabled: true,
                                            text: 'isMapped'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});