/*
 * File: app/view/ExpiryDateWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.ExpiryDateWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.expiryDateWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 500,
    itemId: 'ExpiryDateWindow',
    width: 800,
    title: 'langExpiryDate',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'form',
                            height: 60,
                            itemId: 'companyInfoForm',
                            bodyPadding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    itemId: 'company_name',
                                    fieldLabel: 'companyname',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    itemId: 'expiry_date_rule',
                                    fieldLabel: 'expDaterule',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    itemId: 'product_expiry_rule',
                                    fieldLabel: 'productWxpRule',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    itemId: 'product_rule',
                                    fieldLabel: 'productRule',
                                    labelAlign: 'top'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'expiryDateGrdiContainer',
                            layout: 'fit'
                        },
                        {
                            xtype: 'container',
                            itemId: 'btnContainer',
                            minHeight: 30,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnSet',
                                    margin: '0 5 0 0',
                                    text: 'setLang'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});