/*
 * File: app/view/HelpWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.HelpWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.helpWindow',

    requires: [
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.View',
        'Ext.grid.plugin.CellEditing',
        'Ext.resizer.Splitter',
        'Ext.form.field.HtmlEditor',
        'Ext.form.Panel'
    ],

    height: 500,
    id: 'HelpWindow',
    itemId: 'HelpWindow',
    maxHeight: 1000,
    width: 700,
    title: 'helpWindow',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 40,
                    hidden: true,
                    itemId: 'topButtonContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnHelpTextAdd',
                                    margin: '0 0 0 5',
                                    iconCls: 'yig-add-s-w',
                                    text: 'Add'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 40,
                            width: 309,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'gridContainer',
                    margin: '5 5 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'helpGrid',
                            width: 250,
                            store: 'HelpTextStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'help_code_col',
                                    width: 100,
                                    dataIndex: 'help_code',
                                    menuDisabled: true,
                                    text: 'help_code',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'help_name_col',
                                    dataIndex: 'help_name',
                                    menuDisabled: true,
                                    text: 'helpName',
                                    flex: 1,
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    itemId: 'deleteHelpCol',
                                    width: 50,
                                    menuDisabled: true,
                                    text: 'delCol'
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.CellEditing', {
                                    pluginId: 'plgGridListCellEditing'
                                })
                            ]
                        },
                        {
                            xtype: 'splitter'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    flex: 1,
                                    height: 150,
                                    hidden: true,
                                    itemId: 'helpTextEditor',
                                    enableColors: false,
                                    enableSourceEdit: false
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    componentCls: 'message-list',
                                    hidden: true,
                                    itemId: 'helpTextForm',
                                    autoScroll: true,
                                    layout: 'fit',
                                    bodyPadding: 5,
                                    manageHeight: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnHelpNameSave',
                                    margin: '0 0 0 5',
                                    iconCls: 'yig-save-s-w ',
                                    text: 'save'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 40,
                            itemId: 'bottomBUttonContainer',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    hidden: true,
                                    itemId: 'btnHelpTextSave',
                                    margin: '0 5 0 0',
                                    iconCls: 'yig-save-s-w ',
                                    text: 'save'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    hidden: true,
                                    itemId: 'btnHelpTextEdit',
                                    margin: '0 5 0 0',
                                    iconCls: 'yig-edit-s-w',
                                    text: 'edit'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancel',
                                    margin: '0 5 0 0',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});