/*
 * File: app/view/ImportExportCsvWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.ImportExportCsvWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.importExportCsvWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.plugin.DragDrop',
        'Ext.util.Point',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.CellEditing'
    ],

    height: 500,
    itemId: 'ImportExportCsvWindow',
    width: 600,
    layout: 'fit',
    title: 'ImportExportCsvWindow',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            itemId: 'TableId',
                            fieldLabel: 'Table Id',
                            name: 'table_id'
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 0 0',
                            layout: {
                                type: 'table',
                                columns: 2
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'MappedCombo',
                                    margin: '0 0 10 5',
                                    width: 280,
                                    fieldLabel: 'Mapped From',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    editable: false,
                                    displayField: 'table_name',
                                    hiddenName: 'tableId',
                                    multiSelect: true,
                                    store: 'MappedComboStore',
                                    valueField: 'table_id'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'CsvBillCode',
                                    margin: '0 0 10 10',
                                    width: 280,
                                    fieldLabel: 'Bill Code',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'CsvReportName',
                                    margin: '0 0 0 5',
                                    width: 280,
                                    fieldLabel: 'Report Name',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'ImportExportCsvCombo',
                                    margin: '0 0 0 10',
                                    width: 280,
                                    fieldLabel: 'CSV Type',
                                    allowBlank: false,
                                    editable: false,
                                    displayField: 'type',
                                    queryMode: 'local',
                                    store: 'CsvImportExportComboStore',
                                    valueField: 'id'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '5 5 5 0',
                                    itemId: 'AddCsvBtn',
                                    iconCls: 'yig-add-s-w',
                                    text: 'Add'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            itemId: 'ImportExportCsvGrid',
                            iconCls: '',
                            title: '',
                            store: 'CsvImportExportStore',
                            viewConfig: {
                                plugins: [
                                    Ext.create('Ext.grid.plugin.DragDrop', {

                                    })
                                ]
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'MoveColSelectedCsvImport',
                                    width: 15,
                                    resizable: false,
                                    menuDisabled: true
                                },
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'csvFieldName',
                                    minWidth: 140,
                                    width: '',
                                    dataIndex: 'csv_field_name',
                                    text: 'csv_field_name',
                                    flex: 1,
                                    editor: {
                                        xtype: 'textfield',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'DisplayColCsvImport',
                                    width: 50,
                                    resizable: false,
                                    menuDisabled: true,
                                    text: 'Display_order'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    itemId: 'removeActionCsvImport',
                                    width: 48,
                                    resizable: false,
                                    menuDisabled: true,
                                    text: 'Action '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'field_id',
                                    text: 'mapped_field_id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'csv_mapped_detail_id',
                                    menuDisabled: true,
                                    text: 'csv_mapped_detail_id'
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.CellEditing', {

                                })
                            ]
                        },
                        {
                            xtype: 'container',
                            margins: '10 0 010 0',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '5 5 0 0',
                                    itemId: 'SaveCsvBtn',
                                    iconCls: 'yig-save-s-w',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    margins: '5 0 0 5',
                                    itemId: 'CancelCsvBtn',
                                    icon: '',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});