/*
 * File: app/view/MainPopup.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.MainPopup', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainPopup',

    requires: [
        'Ext.toolbar.Spacer',
        'Ext.form.field.Display',
        'Ext.tab.Panel'
    ],

    id: 'mainPopup',
    itemId: 'mainPopup',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    border: 0,
                    componentCls: 'header-container',
                    height: 50,
                    id: 'topContainer',
                    itemId: 'topContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        padding: '0 0 0 10'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 0,
                            componentCls: 'main-logo-box',
                            height: 35,
                            html: '<a href=\'#dashboard\'><img src="images/ybase-logo.png" style="margin-top:6px;"></a>',
                            itemId: 'main-logobox',
                            margin: '0 10 0 0',
                            width: 125,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: '5 0 0 0'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'orderInfoCnt',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            componentCls: 'x-fld-bold-cls',
                            itemId: 'entryCodeDisplayFld',
                            fieldLabel: 'Entry Code'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'codeCnt',
                            layout: 'fit'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    componentCls: 'control',
                    id: 'controlContainer',
                    itemId: 'controlContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            tabBar: {
                                hidden: true
                            },
                            flex: 1,
                            id: 'bodyTab',
                            itemId: 'bodyTab',
                            ui: 'orange',
                            bodyBorder: true,
                            bodyCls: 'middletab',
                            header: false
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});