/*
 * File: app/view/MsgTabCnt.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.MsgTabCnt', {
    extend: 'Ext.container.Container',
    alias: 'widget.msgTabCnt',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Checkbox',
        'Ext.resizer.Splitter',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea'
    ],

    itemId: 'MsgTabCnt',
    ui: 'addredui',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    tabBar: {
                        items: [
                            {
                                xtype: 'tbspacer',
                                flex: 1
                            },
                            {
                                xtype: 'component',
                                itemId: 'commentCollapseCmp',
                                height: 30,
                                width: 30,
                                componentCls: 'comment-collapse-cmp',
                                html: '<span class="x-tab-newTab-open-btn"></span><span class="collapse-left"></span>'
                            }
                        ]
                    },
                    flex: 1,
                    itemId: 'msgTabPanel',
                    collapseFirst: false,
                    collapsed: false,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'commentTab',
                            collapseFirst: false,
                            title: 'Comment',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'commentTabCnt',
                                    layout: 'fit'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                componentCls: 'no-collapse',
                                itemId: 'commentTabConfig'
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'horensoTab',
                            collapseFirst: false,
                            title: 'Horenso',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    height: 40,
                                    itemId: 'horensoTabTopCnt',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            itemId: 'msgUnionCheckbox',
                                            margin: '2 5 2 5',
                                            fieldLabel: '',
                                            boxLabel: 'union'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'horensoTabCnt',
                                    layout: 'fit'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                componentCls: 'no-collapse',
                                itemId: 'horensoTabConfig'
                            }
                        }
                    ]
                },
                {
                    xtype: 'splitter'
                },
                {
                    xtype: 'panel',
                    height: 140,
                    itemId: 'bottomMsgPanel',
                    animCollapse: false,
                    collapseDirection: 'bottom',
                    collapseFirst: false,
                    collapsed: false,
                    collapsedCls: 'collapsed collapsed_cls',
                    collapsible: true,
                    title: '',
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 30,
                            itemId: 'bottomMsgCnt',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'optMsgCombo',
                                    margin: '2 2 2 5',
                                    width: 80,
                                    fieldLabel: '',
                                    editable: false,
                                    displayField: 'code',
                                    queryMode: 'local',
                                    valueField: 'code'
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'statusComboCnt',
                                    margin: '0 2 0 2',
                                    layout: 'fit'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    hidden: true,
                                    itemId: 'dblRecCheckbox',
                                    margin: '0 0 0 2',
                                    fieldLabel: '',
                                    boxLabel: 'doubleRecord'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            flex: 1,
                            height: 60,
                            itemId: 'msgTabFormPanel',
                            layout: 'fit',
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    itemId: 'ref_record_id',
                                    fieldLabel: 'Label',
                                    name: 'ref_record_id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    itemId: 'table_id',
                                    fieldLabel: 'Label',
                                    name: 'table_id'
                                },
                                {
                                    xtype: 'textareafield',
                                    itemId: 'msgTextarea',
                                    fieldLabel: '',
                                    name: 'comment',
                                    enableKeyEvents: true,
                                    enterIsSpecial: true
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});