/*
 * File: app/view/OrderFileSelectionPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.OrderFileSelectionPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.orderFileSelectionPanel',

    requires: [
        'Ext.panel.Panel',
        'Ext.view.View',
        'Ext.panel.Tool',
        'Ext.resizer.Splitter',
        'Ext.button.Button'
    ],

    componentCls: 'file-selection-pnl-cls',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 1,
                    id: '',
                    itemId: 'fileListPnl',
                    width: 200,
                    layout: 'fit',
                    collapseDirection: 'left',
                    collapsible: true,
                    title: 'Pdf Files',
                    titleCollapse: true,
                    items: [
                        {
                            xtype: 'dataview',
                            itemId: 'fileListView',
                            autoScroll: true,
                            store: 'FileListStore'
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            itemId: 'btnPdfListRefresh',
                            type: 'refresh'
                        }
                    ]
                },
                {
                    xtype: 'splitter'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'bodyContainer',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'component',
                            flex: 1,
                            componentCls: 'file-viewer-cmp-cls',
                            itemId: 'fileViewerCmp',
                            margin: '0 2 0 0 '
                        },
                        {
                            xtype: 'container',
                            componentCls: 'right-cnt-cls',
                            itemId: 'selectedFileListPnl',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'btnActionCnt',
                                    margin: '5 0 5 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'btnProceed',
                                            margin: '0 2 0 0',
                                            ui: 'newbtn-ui',
                                            iconCls: 'yig-add-s-w',
                                            text: 'Proceed'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnSave',
                                            margin: '0 2 0 0',
                                            ui: 'savebtn-ui',
                                            iconCls: 'yig-save-s-w',
                                            text: 'Save'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnCancel',
                                            margin: '0 2 0 0',
                                            ui: 'custom-ui',
                                            iconCls: 'yig-cancel-s-w',
                                            text: 'Cancel'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    componentCls: 'selected-file-list-cnt-cls',
                                    itemId: 'selectedFileListCnt',
                                    margin: '0 2 5 0',
                                    minHeight: 30,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'dataview',
                                            itemId: 'selectedFileListView',
                                            autoScroll: true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});