/*
 * File: app/view/ProductSet.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.ProductSet', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.productSet',

    requires: [
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.resizer.Splitter',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.menu.Menu',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    PanelNo: '6',
    id: 'ProductMap',
    itemId: 'ProductSet',
    ui: 'addredui',
    iconCls: 'yig-list-s-w',
    title: 'Product Set',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'leftStaticCnt',
                    autoScroll: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 40,
                            itemId: 'topBtnCnt',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'SetProductSearchField',
                                    margin: '0 0 0 5',
                                    width: 100,
                                    fieldLabel: ''
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSetProductSearch',
                                    margin: '0 0 0 5',
                                    iconCls: 'yig-search-s-w',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSetProductSave',
                                    margin: '',
                                    iconCls: 'yig-save-s-w',
                                    text: 'Save'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'gridCnt',
                            autoScroll: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'productSetGrid',
                                    margin: '0 0 0 5',
                                    width: 220,
                                    title: '',
                                    store: 'ProductSetStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'set_code',
                                            dataIndex: 'product_code',
                                            menuDisabled: true,
                                            text: 'set code'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'set_name',
                                            dataIndex: 'product_name',
                                            menuDisabled: true,
                                            text: 'set name',
                                            flex: 1
                                        }
                                    ]
                                },
                                {
                                    xtype: 'splitter'
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'productMappedGrid',
                                    margin: '',
                                    title: '',
                                    store: 'ProductMappedStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'product_code',
                                            dataIndex: 'column_5_01',
                                            menuDisabled: true,
                                            text: 'product code',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'product_name',
                                            dataIndex: 'column_5_02',
                                            menuDisabled: true,
                                            text: 'product name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            itemId: 'quantity',
                                            dataIndex: 'quantity',
                                            menuDisabled: true,
                                            text: 'quantity',
                                            format: '0,000',
                                            editor: {
                                                xtype: 'numberfield',
                                                hideTrigger: true,
                                                keyNavEnabled: false,
                                                mouseWheelEnabled: false,
                                                minValue: 0
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'removeAction',
                                            dataIndex: 'string',
                                            menuDisabled: true,
                                            text: 'Remove'
                                        }
                                    ],
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                        })
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'splitter'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'msgListContainer',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            componentCls: 'middle-menu',
                            height: 40,
                            itemId: 'orderOptions',
                            padding: 5,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnRefresh',
                                    ui: 'gridbuttonui',
                                    iconCls: 'icons-v2-refresh',
                                    text: 'Refresh'
                                },
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    hidden: true,
                                    itemId: 'orderOptions1',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            userRights: '50',
                                            itemId: 'btnApplyProcessing',
                                            margin: '0 2 0 0',
                                            ui: 'gridbuttonui',
                                            iconCls: 'icons-v2-processing',
                                            text: 'Processing',
                                            menu: {
                                                xtype: 'menu',
                                                componentCls: 'dropdown-menu',
                                                itemId: 'mnuApplyProcessing',
                                                width: 120
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'btnApplyViewType',
                                            margin: '0 2 0 0',
                                            ui: 'gridbuttonui',
                                            iconCls: 'icons-read',
                                            text: 'More Action',
                                            menu: {
                                                xtype: 'menu',
                                                componentCls: 'dropdown-menu',
                                                itemId: 'mnuApplyViewType',
                                                width: 120
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            userRights: '50',
                                            itemId: 'btnImportCsv',
                                            margin: '0 2 0 0',
                                            ui: 'gridbuttonui',
                                            iconCls: 'icons-upload',
                                            text: 'Upload CSV'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'orderOptions2',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'btnSave',
                                            margin: '0 2 0 0',
                                            iconCls: 'yig-save-s-w',
                                            text: 'Save'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnProductMasterAdd',
                                            margin: '0 2 0 0',
                                            iconCls: 'yig-add-s-w',
                                            text: 'ADD'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnProductImport',
                                            margin: '0 2 0 0',
                                            iconCls: 'yig-import-s-w',
                                            text: 'Import'
                                        },
                                        {
                                            xtype: 'button',
                                            userRights: '1',
                                            itemId: 'btnDownloadCsv',
                                            margin: '0 2 0 0',
                                            iconCls: 'yig-download-s-w',
                                            text: 'Download CSV',
                                            menu: {
                                                xtype: 'menu',
                                                itemId: 'mnuCSV'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'productMasterGridCnt',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    border: 1,
                                    itemId: 'productMasterGrid',
                                    autoScroll: true,
                                    viewConfig: {
                                        getRowClass: function(record, rowIndex, rowParams, store) {
                                            if (!Ext.isEmpty(record.get('mark')) && record.get('mark') == 1)
                                            return "read-row";
                                            else
                                            return "unread-row";
                                        }
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                return '<!--<div class="icons-edit">Edit</div>--><div class="icons-view">View</div>';
                                            },
                                            itemId: 'action',
                                            width: 60,
                                            layout: 'fit',
                                            sortable: false,
                                            menuDisabled: true,
                                            text: 'Action'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (!Ext.isEmpty(value) && value == 1)
                                                return "<div class='read-icon'></div>";
                                                else
                                                return "<div class='unread-icon'></div>";
                                            },
                                            componentCls: 'sortable-col',
                                            itemId: 'mark',
                                            width: 70,
                                            align: 'center',
                                            dataIndex: 'mark',
                                            menuDisabled: true
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            componentCls: 'sortable-col',
                                            itemId: 'icode',
                                            dataIndex: 'icode',
                                            menuDisabled: true
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'occured_date',
                                            dataIndex: 'occured_date',
                                            menuDisabled: true,
                                            text: 'Occ Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'registered_date',
                                            dataIndex: 'registered_date',
                                            menuDisabled: true,
                                            text: 'Reg Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'category',
                                            width: 100,
                                            dataIndex: 'category',
                                            menuDisabled: true,
                                            text: 'Category'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'itemType',
                                            width: 130,
                                            dataIndex: 'item_type',
                                            menuDisabled: true,
                                            text: 'Item Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'created_place',
                                            dataIndex: 'created_place',
                                            menuDisabled: true,
                                            text: 'Created At'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'subject',
                                            minWidth: 350,
                                            width: 350,
                                            dataIndex: 'subject',
                                            menuDisabled: true,
                                            text: 'Subject',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            componentCls: 'sortable-col',
                                            itemId: 'status',
                                            width: 105,
                                            dataIndex: 'status',
                                            menuDisabled: true,
                                            text: 'Status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            noRights: '50',
                                            componentCls: 'sortable-col',
                                            itemId: 'unpublished',
                                            width: 70,
                                            dataIndex: 'unpublished',
                                            menuDisabled: true,
                                            text: 'Unpublished'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '1',
                                            noRights: '50',
                                            componentCls: 'sortable-col',
                                            itemId: 'supervison_department',
                                            width: 110,
                                            dataIndex: 'supervison_department',
                                            menuDisabled: true,
                                            text: 'Supervison Dept'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '50',
                                            componentCls: 'sortable-col',
                                            itemId: 'ans_priority',
                                            width: 90,
                                            dataIndex: 'ans_priority',
                                            menuDisabled: true,
                                            text: 'Ans Priority'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '50',
                                            componentCls: 'sortable-col',
                                            itemId: 'awardType',
                                            width: 70,
                                            dataIndex: 'award_type',
                                            menuDisabled: true,
                                            text: 'Award Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            userRights: '50',
                                            componentCls: 'sortable-col',
                                            itemId: 'related_branch',
                                            width: 120,
                                            dataIndex: 'related_branch',
                                            menuDisabled: true,
                                            text: 'Rel Branch'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});