/*
 * File: app/view/ServiceEntryWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.ServiceEntryWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.serviceEntryWindow',

    requires: [
        'Ext.button.Button',
        'Ext.form.field.Checkbox',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.panel.Tool'
    ],

    componentCls: 'window-maximize',
    iconCls: 'yig-supply-entry-s-w',
    title: 'Service Entry Window',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    componentCls: 'btn-container',
                    itemId: 'actionBtnContainer',
                    padding: 5,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'topMainCnt'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'btnAddComment',
                            margin: '5 5 0 5',
                            ui: 'newbtn-ui',
                            iconCls: 'yig-comment-s-w',
                            text: 'Comment',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'component',
                            flex: 1,
                            componentCls: 'latest-comment-cmp',
                            itemId: 'latestCommentCmp',
                            margin: '5 5 0 5'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'respMsgCnt',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'component',
                                    flex: 1,
                                    itemId: 'msgCmp'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxfield',
                            componentCls: 'autoSaveCmpCls',
                            hidden: true,
                            itemId: 'autoSaveChkbox',
                            margin: '5 5 0 0 ',
                            boxLabel: 'Auto Save',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'btnNew',
                            margin: '5 5 0 0',
                            ui: 'newbtn-ui',
                            iconCls: 'yig-add-s-w',
                            text: 'New',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            itemId: 'btnSave',
                            margin: '5 5 0 0',
                            ui: 'savebtn-ui',
                            iconCls: 'yig-save-s-w',
                            text: 'Save',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            itemId: 'btnNewOrderEntry',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-add-s-w',
                            text: 'New Order Entry',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnClone',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-clone-s-w',
                            text: 'Clone',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnConvertToOrder',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-bill-s-w',
                            text: 'Create Order',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnCreateBill',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-ordernew-s-w',
                            text: 'Creeate Bill',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnSendMail',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-mail-s-w',
                            text: 'Send Mail',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnPrint',
                            margin: '5 5 0 0',
                            ui: 'semi-action-small',
                            iconCls: 'yig-print-ico',
                            text: 'Print',
                            textAlign: 'left',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        hidden: true,
                                        itemId: 'menuItemPrintJson',
                                        text: 'order print json'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        hidden: true,
                                        itemId: 'menuItemPrintCsv',
                                        text: 'client print csv'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        hidden: true,
                                        itemId: 'menuItemOrderPrint',
                                        text: 'client print csv'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            hidden: true,
                            itemId: 'btnDelete',
                            margin: '5 5 0 0',
                            ui: 'delbtn-ui',
                            iconCls: 'yig-cancel-s-w',
                            text: 'Delete',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            componentCls: 'btnproduct',
                            itemId: 'btnCancel',
                            margin: '5 0 0 0',
                            ui: 'custom-ui',
                            iconCls: 'yig-cancel-s-w',
                            text: 'Cancel',
                            textAlign: 'left'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'entryFormContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            itemId: 'entryFormPanel',
                            autoScroll: true,
                            bodyPadding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    itemId: 'id',
                                    fieldLabel: 'Label',
                                    name: 'id'
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'top_screen_container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    hidden: true,
                                    itemId: 'tabContainer',
                                    layout: 'fit'
                                },
                                {
                                    xtype: 'container',
                                    hidden: true,
                                    itemId: 'bottom_screen_container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    margin: '0 4 0 0',
                    cls: 'resize-icon',
                    itemId: 'resizeTool',
                    type: 'maximize'
                }
            ]
        });

        me.callParent(arguments);
    }

});