/*
 * File: app/view/TransferStockWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.TransferStockWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.transferStockWindow',

    requires: [
        'Ext.container.Container',
        'Ext.resizer.Splitter',
        'Ext.button.Button',
        'Ext.panel.Tool'
    ],

    componentCls: 'window-maximize',
    height: 500,
    itemId: 'ExpiryDateWindow',
    width: 800,
    title: 'Stock Transfer Window',
    titleCollapse: false,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'transferProdMasterGridCnt',
                            layout: 'fit'
                        },
                        {
                            xtype: 'splitter'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'transferProdDetailGridCnt',
                            layout: 'fit'
                        },
                        {
                            xtype: 'container',
                            itemId: 'btnContainer',
                            margin: '0 5 0 5',
                            minHeight: 30,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'transferMsgCmpCnt',
                                            minWidth: 300,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnTransferToEntryGrid',
                                                    margin: '2 0 2 0',
                                                    ui: 'savebtn-ui',
                                                    iconCls: 'yig-save-s-w',
                                                    text: 'Save'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    margin: '0 4 0 0',
                    cls: 'resize-icon',
                    itemId: 'transferStockResizeTool',
                    type: 'maximize'
                }
            ]
        });

        me.callParent(arguments);
    }

});