/*
 * File: app/view/UserProfileEdit.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.UserProfileEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.userProfileEdit',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    id: 'UserProfileEdit',
    itemId: 'UserProfileEditWindow',
    width: 429,
    resizable: false,
    title: 'Edit User',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    itemId: 'UserEditForm',
                    width: 400,
                    bodyPadding: 10,
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            itemId: 'UserId',
                            fieldLabel: 'Label',
                            name: 'user_id'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'UserName',
                            margin: '5 5 5 5',
                            fieldLabel: 'User Name',
                            name: 'username',
                            allowBlank: false
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'Password',
                                    margin: '5 5 5 5',
                                    width: 375,
                                    fieldLabel: 'Password',
                                    name: 'password',
                                    inputType: 'password',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    itemId: 'ResetPaswordCkb',
                                    margin: '0 0 0 5',
                                    fieldLabel: '',
                                    name: 'resetpassword',
                                    boxLabel: 'Reset Password'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'LastName',
                            margin: '5 5 5 5',
                            fieldLabel: 'Last Name',
                            name: 'last_name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'FirstName',
                            margin: '5 5 5 5',
                            fieldLabel: 'First Name',
                            name: 'first_name',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'PhoneNo',
                            margin: '5 5 5 5',
                            fieldLabel: 'Phone No.',
                            name: 'phone',
                            emptyText: '00-000-000-0000',
                            maskRe: /^[0-9 -]$/
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'EmailId',
                            margin: '5 5 5 5',
                            fieldLabel: 'Email',
                            name: 'email',
                            vtype: 'email'
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'LanguageSelectCombo',
                            margin: '5 5 5 5',
                            fieldLabel: 'Language',
                            name: 'language',
                            editable: false,
                            displayField: 'name',
                            store: 'AvailableLanguageStore',
                            valueField: 'ID'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'UserSaveBtn',
                            margin: '8 5 8 0',
                            iconCls: 'yig-save-s-w',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'CancelBtn',
                            margin: '8 5 8 0',
                            iconCls: 'yig-cancel-s-w',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});