/*
 * File: app/model/ProductMappedModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.model.ProductMappedModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'product_set_id'
        },
        {
            name: 'product_master_id'
        },
        {
            name: 'product_id'
        },
        {
            name: 'quantity'
        },
        {
            name: 'column_5_01'
        },
        {
            name: 'column_5_02'
        }
    ]
});