/*
 * File: app/view/ImageDragDropWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.ImageDragDropWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.imageDragDropWindow',

    requires: [
        'Ext.container.Container'
    ],

    cls: 'dragdrop-window',
    componentCls: 'dragdrop-window',
    height: 350,
    id: 'imageDragDropWindow',
    itemId: 'imageDragDropWindow',
    width: 450,
    resizable: false,
    closeAction: 'hide',
    header: false,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    cls: 'file-dropzone',
                    componentCls: 'file-dropzone',
                    height: 338,
                    itemId: 'dropElementContainer',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            componentCls: ' multifileContainer',
                            itemId: 'multifileContainer',
                            layout: {
                                type: 'hbox',
                                align: 'bottom',
                                pack: 'center'
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});