/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.MainPanel', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainPanel',

    requires: [
        'Ext.toolbar.Spacer',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.TextArea',
        'Ext.resizer.Splitter',
        'Ext.form.field.ComboBox',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.CellEditing'
    ],

    id: 'mainPanel',
    itemId: 'mainPanel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    border: 0,
                    componentCls: 'header-container',
                    height: 50,
                    id: 'topContainer',
                    itemId: 'topContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        padding: '0 0 0 10'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 0,
                            componentCls: 'main-logo-box',
                            height: 35,
                            html: '<a href=\'#dashboard\'><img src="images/ybase-logo.png" style="margin-top:6px;"></a>',
                            itemId: 'main-logobox',
                            margin: '0 10 0 0',
                            width: 125,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: '5 0 0 0'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            flex: 0,
                            id: 'TopButtonContainer',
                            itemId: 'TopButtonContainer',
                            margin: '0 10 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'orderEntryMenuItem',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-supply-entry',
                                    scale: 'medium',
                                    text: 'Order Entry'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'salesEntryMenuItem',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-supply-entry',
                                    scale: 'medium',
                                    text: 'Sales Entry'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnEntry',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-supply-entry',
                                    scale: 'medium',
                                    text: 'Entry Panel',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuOrderEntry',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuSalesEntry',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCustomer',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-customer',
                                    scale: 'medium',
                                    text: 'Customer'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnOrderMaster',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_order_list',
                                    scale: 'medium',
                                    text: 'Sales',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'orderMasterMenuItem',
                                                iconCls: 'yig-order-s-b',
                                                text: 'Order Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'salesMasterMenuItem',
                                                iconCls: 'yig-order-s-b',
                                                text: 'salesMaster'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                itemId: 'orderDetailMenuItem',
                                                iconCls: 'yig-order-detail-s-b',
                                                text: 'Order Detail'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'serivceMasterMenuItem',
                                                iconCls: 'yig-service-s-b',
                                                text: 'Service Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'repairMasterPnlMenuItem',
                                                iconCls: 'yig-repair-s-b',
                                                text: 'Repair Master'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnStore',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_order_list',
                                    scale: 'medium',
                                    text: 'Store',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'productPnlMenuItem',
                                                iconCls: 'yig-product-set-s-b',
                                                text: 'Product'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'purchaseEntryPnlMenuItem',
                                                iconCls: 'yig-supply-entry-s-b',
                                                text: 'New Purchase'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'batchMasterPnlMenuItem',
                                                iconCls: 'yig-invoicelist-s-b',
                                                text: 'Batch Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                itemId: 'batchDetailPnlMenuItem',
                                                iconCls: 'yig-order-detail-s-b',
                                                text: 'Batch Detail'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'supplierPnlMenuItem',
                                                iconCls: ' yig-supply-list-s-b',
                                                text: 'Supplier'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnStoreTransfer',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-transfer',
                                    scale: 'medium',
                                    text: 'Store Transfer ',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'stockTransferEntryPnlMenuItem',
                                                iconCls: 'yig-supply-entry-s-b',
                                                text: 'New Transfer Entry'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'stockTransferMasterPnlMenuItem',
                                                iconCls: 'yig-transaction-s-b',
                                                text: 'Transfer Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                itemId: 'stockTransferDetailPnlMenuItem',
                                                iconCls: 'yig-order-detail-s-b',
                                                text: 'Transfer Detail'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnSupport',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-support',
                                    scale: 'medium',
                                    text: 'Support',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'serivceMasterMenuItem1',
                                                iconCls: 'yig-service-s-b',
                                                text: 'Service Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'repairMasterPnlMenuItem1',
                                                iconCls: 'yig-repair-s-b',
                                                text: 'Repair Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                itemId: 'stockTransferDetailPnlMenuItem',
                                                iconCls: 'yig-order-detail-s-b',
                                                text: 'Transfer Detail'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnReport',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-report',
                                    scale: 'medium',
                                    text: 'Report'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnBilling',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_billing',
                                    scale: 'medium',
                                    text: 'billing',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'invoiceMenuItem',
                                                iconCls: 'yig-order-invoice-s-b',
                                                text: 'productList'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'paymentMenuItem',
                                                iconCls: 'yig-order-payment-s-b',
                                                text: 'productList'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'transactionMenuItem',
                                                iconCls: 'yig-order-transaction-s-b',
                                                text: 'transaction'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnSupplier',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_supplier',
                                    scale: 'medium',
                                    text: 'Supplier',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'supplyEntryMenuItem',
                                                iconCls: 'yig-supply-entry-s-b',
                                                text: 'Supply Entry'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'purchaseEntryMenuItem',
                                                iconCls: 'yig-supply-entry-s-b',
                                                text: 'Purchase Entry'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'supplyListPanelItem',
                                                iconCls: 'yig-supply-list-s-b',
                                                text: 'Supplier List'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnPurchaseBilling',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_purchase_billing',
                                    scale: 'medium',
                                    text: 'Purchase Billing',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'payableBillMenuItem',
                                                iconCls: 'yig-payable-bill-s-b',
                                                text: 'Payable Bill'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'purchasePaymentMenuItem',
                                                iconCls: 'yig-purchase-payment-s-b',
                                                text: 'Purchase Payment'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'purchaseTransactionMenuItem',
                                                iconCls: 'yig-purchase-transaction-s-b',
                                                text: 'Purchase Transaction'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnAccount',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_account',
                                    scale: 'medium',
                                    text: 'Account',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'accTranasctionMenuItem',
                                                iconCls: 'yig-acc-transaction-s-b',
                                                text: 'transaction List'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'customerAccStatementMenuItem',
                                                iconCls: 'yig-customner-acc-statement-s-b',
                                                text: 'Customer Acc statement'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnMessage',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon-messsage',
                                    scale: 'medium',
                                    text: 'payment'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnSettings',
                                    margin: '0 5 0 0',
                                    iconCls: 'yig-setting-m-w',
                                    scale: 'medium',
                                    text: 'settings'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnPickingList',
                                    margin: '0 5 0 0',
                                    iconCls: 'icon_supplier',
                                    scale: 'medium',
                                    text: 'Picking List',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'pickingEntryMenuItem',
                                                iconCls: 'yig-picking-entry-s-b',
                                                text: 'Picking Entry'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'pickingMasterMenuItem',
                                                iconCls: 'yig-picking-order-master-s-b',
                                                text: 'Picking Master'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'pickingDetailMenuItem',
                                                iconCls: 'yig-picking-detail-list-s-b',
                                                text: 'Picking Detail'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMenuAcc',
                                    iconCls: 'icons-user',
                                    scale: 'medium',
                                    text: 'Profile',
                                    menu: {
                                        xtype: 'menu',
                                        showSeparator: false,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                componentCls: 'help-btn',
                                                itemId: 'menuUserProfile',
                                                iconCls: 'icon_user_profile',
                                                text: 'profile'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                componentCls: 'help-btn',
                                                hidden: true,
                                                itemId: 'menuSwitchUser',
                                                iconCls: 'icon_switch_user',
                                                text: 'switchUser'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                componentCls: 'help-btn',
                                                itemId: 'menuSignOut',
                                                iconCls: 'yig-logout-s-b',
                                                text: 'Sign Out'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    componentCls: 'control',
                    id: 'controlContainer',
                    itemId: 'controlContainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            id: 'bodyTab',
                            itemId: 'bodyTab',
                            ui: 'orange',
                            bodyBorder: true,
                            bodyCls: 'middletab',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    PanelNo: '200',
                                    id: 'DashBoardPanel',
                                    itemId: 'DashBoardPanel',
                                    padding: '0 0 5 0',
                                    title: 'My Tab',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    tabConfig: {
                                        xtype: 'tab',
                                        iconCls: 'yig-dashboard-s-w'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            height: 250,
                                            itemId: 'leftContainer1',
                                            margin: '0 5 5 5',
                                            width: 400,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 40,
                                                    itemId: 'actionBtnContainer1',
                                                    margin: '0 5 0 0 ',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    componentCls: 'dashoadNote',
                                                    layout: 'fit',
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            componentCls: 'text-area-note',
                                                            id: 'DasboardNote',
                                                            itemId: 'DasboardNote1',
                                                            margin: '0 0 0 5',
                                                            padding: '0 0 5 0'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 339,
                                            itemId: 'rightContainer1',
                                            width: 355,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 40,
                                                    itemId: 'btnRightContainer1',
                                                    padding: '5 0 5 0',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch',
                                                        pack: 'end'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            margin: '0 5.5 0 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch',
                                                                pack: 'end'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    hidden: true,
                                                                    itemId: 'btnMessageEdit',
                                                                    margin: '0 5 0 0',
                                                                    ui: 'custom-ui',
                                                                    iconCls: 'yig-edit-s-w',
                                                                    text: ''
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    cls: 'refresh-btn btnproduct',
                                                                    hidden: true,
                                                                    itemId: 'btnDashBoardRefresh',
                                                                    iconCls: 'yig-refresh-s-w',
                                                                    text: 'Refresh'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    height: 659,
                                                    itemId: 'MessagePanel',
                                                    minHeight: 250,
                                                    padding: '0 0 5 0',
                                                    autoScroll: true,
                                                    bodyPadding: 10,
                                                    title: ''
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'splitter',
                            hidden: true,
                            itemId: 'bodySkuSplit'
                        },
                        {
                            xtype: 'panel',
                            tabBar: {
                                iconCls: 'sku-cmp-panel-collapse',
                                componentCls: 'sku-cmp-panel'
                            },
                            componentCls: 'sku-panel ',
                            hidden: true,
                            itemId: 'msgCmpPanel',
                            width: 680,
                            layout: 'fit',
                            animCollapse: false,
                            collapseDirection: 'left',
                            collapsed: true,
                            collapsedCls: 'collapsed bulk-right  collapsed_cls',
                            collapsible: true,
                            title: '',
                            titleCollapse: true
                        },
                        {
                            xtype: 'panel',
                            componentCls: 'bulk-panel',
                            hidden: true,
                            itemId: 'BlukUpdatePanel',
                            margin: '',
                            width: 355,
                            animCollapse: false,
                            collapseDirection: 'left',
                            collapseFirst: false,
                            collapsed: false,
                            collapsedCls: 'collapsed bulk-right collapsed_cls',
                            header: {
                                componentCls: 'bulkpanel-hide'
                            },
                            iconCls: 'bulk-hide',
                            title: 'Bulk Update',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    border: 1,
                                    componentCls: 'bulk-panel-down',
                                    itemId: 'BulkUpdateDownPanel',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 32,
                                            itemId: 'BulkUpdateDownTopPnl',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 32,
                                                    itemId: 'SelectFieldPnl',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'previousComboValueBtn',
                                                            margin: '0 2 0 10',
                                                            width: 30,
                                                            iconCls: 'previous-value',
                                                            text: 'left'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            itemId: 'FieldCombo',
                                                            margin: '10 0 0 0',
                                                            labelWidth: 48,
                                                            displayField: 'field_label',
                                                            queryMode: 'local',
                                                            store: 'FieldListJson',
                                                            valueField: 'column_name'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'nextComboValueBtn',
                                                            margin: '0 10 0 2',
                                                            width: 30,
                                                            iconCls: 'next-value',
                                                            text: 'right'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            hidden: true,
                                                            itemId: 'GetFieldButton',
                                                            margin: '0 10 0 0',
                                                            text: 'Get'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 32,
                                            itemId: 'SelectFieldPnl1',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'radiogroup',
                                                    margin: '0 0 0 10',
                                                    width: 232,
                                                    labelWidth: 60,
                                                    items: [
                                                        {
                                                            xtype: 'radiofield',
                                                            itemId: 'ReplaceValueRadioBox',
                                                            boxLabel: 'Replace Value',
                                                            checked: true
                                                        },
                                                        {
                                                            xtype: 'radiofield',
                                                            itemId: 'SpecifiedFormatCheckvalue',
                                                            boxLabel: 'Specified Format'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'SetButton',
                                                    iconCls: 'yig-set-s-w',
                                                    text: 'Set'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'undo',
                                                    margin: '0 15 0 0',
                                                    iconCls: 'yig-revert-s-w'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 30,
                                            itemId: 'SetPanel',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'NumberCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'ReplaceValueNumeric',
                                                            margin: '0 80 0 10',
                                                            labelWidth: 60
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'ComboCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'DateCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'datefield',
                                                            itemId: 'ReplaceValueDate',
                                                            margin: '0 80 0 10',
                                                            labelWidth: 60
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    itemId: 'TextCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'ReplaceValueTextBox',
                                                            margin: '0 80 0 10',
                                                            width: 235
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 30,
                                            hidden: true,
                                            itemId: 'AdvanceFieldPanel',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'NumberPanel',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'checkboxfield',
                                                            flex: 1,
                                                            itemId: 'PercentagecheckBox',
                                                            margin: '0 0 0 10',
                                                            fieldLabel: 'Percentage (%)',
                                                            boxLabel: 'Box Label'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            flex: 1,
                                                            itemId: 'numberText',
                                                            margin: '0 80 0 20',
                                                            fieldLabel: 'Label'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'DatePanel',
                                                    margin: '0 0 0 30',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'AddDaysText',
                                                            margin: '0 80 0 10',
                                                            fieldLabel: 'Add Days',
                                                            labelWidth: 80
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: 26,
                                                    itemId: 'TextPanel',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            margins: '0 0 0 10',
                                                            itemId: 'TextText',
                                                            width: 235,
                                                            labelWidth: 45
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            itemId: 'AtFrontCheckBox',
                                                            margin: '0 30 0 30',
                                                            fieldLabel: 'At Front',
                                                            labelWidth: 40
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'SelectedGridPanel',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    itemId: 'SelectedFieldGrid',
                                                    margin: '10 10 10 10',
                                                    disableSelection: true,
                                                    store: 'SelectedValueJson',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            resizable: false,
                                                            dataIndex: 'FieldSelectedValue',
                                                            menuDisabled: true,
                                                            text: 'FieldSelectedValue',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            resizable: false,
                                                            dataIndex: 'ReplaceValue',
                                                            menuDisabled: true,
                                                            text: 'ReplaceValue',
                                                            flex: 1,
                                                            editor: {
                                                                xtype: 'textfield'
                                                            }
                                                        }
                                                    ],
                                                    plugins: [
                                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                                        })
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});