/*
 * File: app/view/PrintReportPopUp.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.PrintReportPopUp', {
    extend: 'Ext.window.Window',
    alias: 'widget.printReportPopUp',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.button.Button'
    ],

    componentCls: 'window-maximize',
    itemId: 'PrintReportPopUp',
    title: 'Print Report Window',
    titleCollapse: false,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    itemId: 'printMainCnt',
                    standardSubmit: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'topFieldCnt',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    itemId: 'storeListCombo',
                                    margin: '5 5 5 5',
                                    name: 'store_id',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    displayField: 'name',
                                    queryMode: 'local',
                                    store: 'StoreListStore',
                                    valueField: 'code'
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 0,
                                    itemId: 'printDateField',
                                    margin: '5 5 5 5',
                                    width: 167,
                                    name: 'date',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    format: 'Y-m-d'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'btnPrintReportCnt',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'btnPrintReport',
                                            margin: '5 5 5 5',
                                            text: 'Print'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});