/*
 * File: app/model/CsvImportExportModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.model.CsvImportExportModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'csv_field_name'
        },
        {
            name: 'field_id'
        },
        {
            name: 'csv_report_field_id'
        },
        {
            name: 'display_order'
        },
        {
            name: 'csv_report_id'
        },
        {
            name: 'is_single_mapped'
        }
    ]
});