/*
 * File: app/model/EcSiteModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.model.EcSiteModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'csv_field_name'
        },
        {
            name: 'table_id'
        },
        {
            name: 'field_id'
        },
        {
            name: 'csv_report_field_id'
        },
        {
            name: 'is_single_mapped'
        },
        {
            name: 'csv_report_id'
        },
        {
            name: 'table_field_id'
        },
        {
            name: 'field_label'
        },
        {
            name: 'mapped_fields'
        },
        {
            name: 'mapped_table_id'
        },
        {
            name: 'is_mapped'
        },
        {
            name: 'display_order'
        },
        {
            name: 'default_value'
        },
        {
            name: 'option_value'
        },
        {
            name: 'id_field_table'
        },
        {
            name: 'xtype'
        },
        {
            name: 'mapped_table_name'
        },
        {
            name: 'format_id'
        },
        {
            name: 'format_name'
        },
        {
            name: 'max_length'
        }
    ]
});