/*
 * File: app/model/UserInfoModel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.model.UserInfoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'staff_name'
        },
        {
            name: 'email'
        },
        {
            name: 'branch_code'
        },
        {
            name: 'branch_name'
        },
        {
            name: 'department_code'
        },
        {
            name: 'department_name'
        },
        {
            name: 'station_code'
        },
        {
            name: 'station_name'
        },
        {
            name: 'group_code'
        },
        {
            name: 'group_name'
        },
        {
            name: 'post_code'
        },
        {
            name: 'post_name'
        },
        {
            name: 'staff_id'
        }
    ]
});