/*
 * File: app/view/CsvImportWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.CsvImportWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.CsvImportWin',

    requires: [
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    height: 140,
    itemId: 'CsvImportWin',
    width: 480,
    title: 'CSV Import',

    layout: {
        type: 'vbox',
        align: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            style: {
                background: '#ffffff'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 0,
                    margins: '8',
                    height: 20,
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'subHeading',
                            value: 'Browse xlsx file'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 0,
                    itemId: 'CsvImpForm',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 0,
                            itemId: 'updContainer',
                            margin: 5,
                            items: [
                                {
                                    xtype: 'filefield',
                                    itemId: 'csvFile',
                                    margin: '1 0 0 0',
                                    width: 250,
                                    fieldLabel: '',
                                    name: 'csvFile',
                                    validateBlank: true,
                                    buttonMargin: 4
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'updControls',
                            margin: '0 5',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnUpload',
                                    margin: '0 2 0 0',
                                    text: 'Upload'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancel',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});