/*
 * File: app/store/SettingsPanelStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.store.SettingsPanelStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'SettingsPanelStore',
            data: [
                // {
                //     buttons: Ext.LANG.settingsPanel.btnProductList,
                //     route: 'ProductMaster',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnProductSet,
                //     route: 'SetProduct',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnItemList,
                //     route: 'ItemList',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnItemSizeSelection,
                //     route: 'ItemSizeSelection',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnCompanyList,
                //     route: 'CompanyList',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                {
                    buttons: Ext.LANG.settingsPanel.btnClientMaster,
                    route: 'clientMaster',
                    iconClass: 'yig-client-s-w',
                    userRole: '50',
                    menuItemId: 'menuClientMaster'
                },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnProductMaster,
                //     route: 'productMaster',
                //     iconClass: 'yig-product-s-w',
                //     userRole: '50',
                //     menuItemId: 'menuProductMaster'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnCsvMap,
                //     route: 'csvMap',
                //     iconClass: 'yig-csv-s-w',
                //     userRole: '50',
                //     menuItemId: 'menuCsvMap'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnStaff,
                //     route: 'staff',
                //     iconClass: 'yig-staff-s-w',
                //     userRole: '50',
                //     menuItemId: 'menuStaff'
                // }
                // {
                //     buttons: Ext.LANG.settingsPanel.btnSupplierMaster,
                //     route: 'SupplierMaster',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '100'
                // },
                // {
                //     buttons: Ext.LANG.settingsPanel.btnDelivaryAddress,
                //     route: 'DelivaryAddress',
                //     iconClass: 'yig-list-s-w',
                //     userRole: '50'
                // },
                /*{
                    buttons: Ext.LANG.settingsPanel.btnReportLog,
                    route: 'ReportLog',
                    iconClass: 'yig-list-s-w',
                    userRole: '100'
                },
                {
                    buttons: Ext.LANG.settingsPanel.btnHoliday,
                    route: 'Holiday',
                    iconClass: 'yig-list-s-w',
                    userRole: '50'
                }*/
               /* {
                    buttons: Ext.LANG.settingsPanel.btnCategory,
                    route: 'Category',
                    iconClass: 'yig-list-s-w',
                    userRole: '50'
                },*/
              /*  {
                    buttons: Ext.LANG.settingsPanel.btnMailSettings,
                    route: 'mailSystem',
                    iconClass: 'yig-list-s-w',
                    userRole: '50'
                }*/
            ],
            fields: [
                {
                    name: 'buttons'
                },
                {
                    name: 'route'
                },
                {
                    name: 'iconClass'
                },
                {
                    name: 'userRole'
                },
                {
                    name: 'menuItemId'
                }
            ]
        }, cfg)]);
    }
});