/*
 * File: app/view/DashBoardEditWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.DashBoardEditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.dashBoardEditWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.HtmlEditor',
        'Ext.button.Button'
    ],

    frame: true,
    height: 578,
    itemId: 'DashBoardEditWindow',
    width: 400,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    itemId: 'DashBoardEditForm',
                    bodyPadding: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            minHeight: 240,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    flex: 1,
                                    name: 'message',
                                    enableAlignments: false,
                                    enableColors: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    componentCls: 'btnproduct',
                                    id: 'btnDBSave',
                                    itemId: 'btnDBEditSave',
                                    ui: 'savebtn-ui',
                                    iconCls: 'yig-save-s-w',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnDBCancel',
                                    itemId: 'btnDBCancel',
                                    margin: '0 0 0 10',
                                    ui: 'custom-ui',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});