/*
 * File: app/view/SearchEditWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.SearchEditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.searchEditWindow',

    requires: [
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.View',
        'Ext.grid.plugin.CellEditing'
    ],

    height: 400,
    itemId: 'SearchEditWindow',
    width: 700,
    layout: 'fit',
    title: 'SearchEditWindow',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'mainCnt',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 50,
                            itemId: 'headerCnt',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnAdd',
                                    margin: '0 0 0 5',
                                    ui: 'newbtn-ui-small',
                                    iconCls: 'yig-add-s-w',
                                    text: 'Add'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSave',
                                    margin: '0 5 0 5',
                                    ui: 'savebtn-ui-small',
                                    iconCls: 'yig-save-s-w',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancel',
                                    margin: '0 5 0 0',
                                    ui: 'custom-ui',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'Cancel'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'bodyCnt',
                            margin: '0 5 5 5 ',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'searchCriteriaGrid',
                                    margin: '0 0 0 5',
                                    width: 240,
                                    title: '',
                                    store: 'SearchCriteriaStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'moveColSelected',
                                            width: 20,
                                            menuDisabled: true,
                                            text: ''
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'usernameCol',
                                            dataIndex: 'username',
                                            menuDisabled: true,
                                            text: 'username'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'searchNameCol',
                                            dataIndex: 'search_name',
                                            menuDisabled: true,
                                            text: 'SearchName',
                                            editor: {
                                                xtype: 'textfield',
                                                itemId: 'searchNameEditor',
                                                allowBlank: false
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'searchCriteriaCol',
                                            width: 60,
                                            dataIndex: 'search_criteria',
                                            menuDisabled: true,
                                            text: 'SearchCriteria',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield',
                                                itemId: 'searchCriteriaEditor'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'displayCol',
                                            width: 60,
                                            menuDisabled: true,
                                            text: 'displayCol'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            itemId: 'systemFlagCol',
                                            width: 60,
                                            dataIndex: 'system_flg',
                                            menuDisabled: true,
                                            text: 'systemFlag'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'isPublicCol',
                                            width: 60,
                                            dataIndex: 'is_public',
                                            menuDisabled: true,
                                            text: 'isPublic'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'showTemplateCol',
                                            width: 60,
                                            dataIndex: 'show_template',
                                            menuDisabled: true,
                                            text: 'showTemplate'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            itemId: 'removeAction',
                                            width: 40,
                                            menuDisabled: true,
                                            text: 'remove'
                                        }
                                    ],
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.CellEditing', {
                                            pluginId: 'plgGridListCellEditing'
                                        })
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});