/*
 * File: app/model/SearchCriteriaModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.model.SearchCriteriaModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'search_id'
        },
        {
            name: 'search_name'
        },
        {
            name: 'search_criteria'
        },
        {
            name: 'system_flg'
        },
        {
            name: 'is_public'
        },
        {
            name: 'show_template'
        },
        {
            name: 'datagrid_id'
        },
        {
            name: 'user_id'
        },
        {
            name: 'delete_flg'
        },
        {
            name: 'username'
        }
    ]
});