<?php

return array(
        'file_type' =>'png',
        'dpi'       =>72,
        'thickness' =>40,
        'scale'     =>'1',
        'font_size' =>'12',
        'font_name' =>'Arial.ttf',
        'start_day' =>20,
        'start_month'=>50,
        'day' => array(
                        '1'     => 'A',
                        '2'     => 'B',
                        '3'     => 'C',
                        '4'     => 'D',
                        '5'     => 'E',
                        '6'     => 'F',
                        '7'     => 'G',
                        '8'     => 'H',
                        '9'     => 'I',
                        '10'    => 'J',
                        '11'    => 'K',
                        '12'    => 'L',
                        '13'    => 'M',
                        '14'    => 'N',
                        '15'    => 'O',
                        '16'    => 'P',
                        '17'    => 'Q',
                        '18'    => 'R',
                        '19'    => 'S',
                        '20'    => 'T',
                        '21'    => 'U',
                        '22'    => 'V',
                        '23'    => 'W',
                        '24'    => 'X',
                        '25'    => 'Y',
                        '26'    => 'Z',
                        '27'    => 'AA',
                        '28'    => 'BB',
                        '29'    => 'CC',
                        '30'    => 'DD',
                        '31'    => 'EE',
                    ),
        'month' => array(
                        '1'     => 'O',
                        '2'     => 'P',
                        '3'     => 'Q',
                        '4'     => 'R',
                        '5'     => 'S',
                        '6'     => 'T',
                        '7'     => 'U',
                        '8'     => 'V',
                        '9'     => 'W',
                        '10'    => 'X',
                        '11'    => 'Y',
                        '12'    => 'Z',
                    ),
        'trim_data' => 40,
        'trim_product_name' => 88,
        'trim_brand_name'   => 60,
        'trim_english_name' => 45,
        'gcode_display' => false,
        );

