/*
 * File: app/store/FieldOptionDataStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.store.FieldOptionDataStore', {
    extend: 'Ext.data.Store',

    requires: [
        'YBase.model.FieldOptionDataModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'YBase.model.FieldOptionDataModel',
            storeId: 'FieldOptionDataStore',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'bizlayer/fieldOption/getFieldOptionData',
                    create: 'bizlayer/fieldOption/gridUpdate',
                    update: 'bizlayer/fieldOption/gridUpdate',
                    destroy: 'bizlayer/fieldOption/gridUpdate'
                },
                url: 'bizlayer/fieldOption/getFieldOptionData',
                reader: {
                    type: 'json',
                    root: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});