/*
 * File: app/view/SettingsPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.SettingsPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.settingsPanel',

    requires: [
        'Ext.XTemplate',
        'Ext.button.Button',
        'Ext.resizer.Splitter',
        'Ext.tab.Panel',
        'Ext.toolbar.Spacer',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.column.Column',
        'Ext.form.field.ComboBox',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.form.field.Date'
    ],

    PanelNo: '100',
    id: 'SettingsPanel',
    itemId: 'SettingsPanel',
    width: 941,
    autoScroll: true,
    iconCls: 'yig-setting-s-w',
    title: 'Settings Panel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'leftContainer',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            componentCls: 'setting-side-bar',
                            width: 200,
                            animCollapse: false,
                            collapseDirection: 'left',
                            collapsible: true,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'dataview',
                                    flex: 1,
                                    autoShow: true,
                                    itemId: 'settingsDataView',
                                    tpl: [
                                        '<tpl for=".">',
                                        '    <div class="settingSelector-div">',
                                        '        <tpl if="this.isNewGroup(values)">',
                                        '            {[this.setGroup(values)]}',
                                        '            <tpl if="this.isNotfirstItem(xindex)">',
                                        '            </div>',
                                        '        </tpl>',
                                        '        <div class="test">',
                                        '        </tpl>',
                                        '        <div class="settingsButtons">',
                                        '',
                                        '            <div class="image-tpl"><span class="settingSprite {iconClass}"></span> <span class="settings-buttons">{buttons}</span></div>',
                                        '        </div>',
                                        '        <tpl if="this.isLastItem(xindex, xcount)">',
                                        '        </div> //closing for previous div',
                                        '    </tpl>',
                                        '</div>',
                                        '</tpl>'
                                    ],
                                    itemSelector: 'div.settingSelector-div',
                                    store: 'SettingsPanelStore'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    hidden: true,
                                    itemId: 'btnsContainer',
                                    margin: '5 5 5 5',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnProductList',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Product List',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnProductSet',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Set Product',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnCompanyList',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Company List',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnCompanyProductList',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Company Product List',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnSupplierMaster',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Supplier Master',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnDelivaryAddress',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Delivary Address',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnCsvMap',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-csv-s-w',
                                            text: 'CSV-Import/Export Mapping',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnDataSync',
                                            margin: '0 0 5 0',
                                            iconCls: 'yig-sync-s-w',
                                            text: 'Master Data import/export',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnManageCompanyProduct',
                                            iconCls: 'yig-list-s-w',
                                            text: 'CompanyProductManage',
                                            textAlign: 'left'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnReportLog',
                                            iconCls: 'yig-list-s-w',
                                            text: 'Report Log',
                                            textAlign: 'left'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'splitter',
                    hidden: true
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            id: 'SettingsBodyTab',
                            itemId: 'settingsBodyTab',
                            closeAction: 'hide'
                        },
                        {
                            xtype: 'panel',
                            componentCls: 'bulk-panel',
                            hidden: true,
                            itemId: 'BlukUpdatePanel',
                            margin: '',
                            width: 355,
                            animCollapse: false,
                            collapseDirection: 'left',
                            collapsed: true,
                            collapsedCls: 'collapsed bulk-right',
                            collapsible: true,
                            title: 'Bulk Update',
                            titleCollapse: true,
                            layout: {
                                type: 'vbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    border: 1,
                                    componentCls: 'bulk-panel-top',
                                    hidden: true,
                                    itemId: 'BulkUpdateTopPanel',
                                    collapsed: false,
                                    collapsible: true,
                                    title: 'Copy Clicked Value',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    itemId: 'GetClickItemCheckBox',
                                                    margin: '10 10 10 10',
                                                    boxLabel: 'Get clicked item value'
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'CopyClearBtn',
                                                    margin: '0 10 0 0',
                                                    iconCls: 'winstonebase-clear',
                                                    text: 'Clear'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            itemId: 'SelectedValuesGrid',
                                            margin: '0 10 10 10',
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                mode: 'SINGLE',
                                                showHeaderCheckbox: false
                                            }),
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.CellEditing', {

                                                })
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 229,
                                                    resizable: false,
                                                    dataIndex: 'CopiedValue',
                                                    menuDisabled: true,
                                                    text: 'Copied Value',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'textfield',
                                                        itemId: 'CopedValueTxt'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    itemId: 'BulkUpdateActionColumn',
                                                    width: 51,
                                                    resizable: false,
                                                    menuDisabled: true,
                                                    text: 'Action'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    border: 1,
                                    componentCls: 'bulk-panel-down',
                                    itemId: 'BulkUpdateDownPanel',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 32,
                                            itemId: 'BulkUpdateDownTopPnl',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 32,
                                                    itemId: 'SelectFieldPnl',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            itemId: 'FieldCombo',
                                                            margin: '10 10 0 10',
                                                            labelWidth: 48,
                                                            displayField: 'field_label',
                                                            queryMode: 'local',
                                                            store: 'FieldListJson',
                                                            valueField: 'column_name'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            hidden: true,
                                                            itemId: 'GetFieldButton',
                                                            margin: '0 10 0 0',
                                                            text: 'Get'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 32,
                                            itemId: 'SelectFieldPnl1',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'radiogroup',
                                                    margin: '0 0 0 10',
                                                    width: 232,
                                                    labelWidth: 60,
                                                    items: [
                                                        {
                                                            xtype: 'radiofield',
                                                            itemId: 'ReplaceValueRadioBox',
                                                            boxLabel: 'Replace Value',
                                                            checked: true
                                                        },
                                                        {
                                                            xtype: 'radiofield',
                                                            itemId: 'SpecifiedFormatCheckvalue',
                                                            boxLabel: 'Specified Format'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'SetButton',
                                                    iconCls: 'winstonebase-set',
                                                    text: 'Set'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'undo',
                                                    margin: '0 15 0 0',
                                                    iconCls: 'yig-reset'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 30,
                                            itemId: 'SetPanel',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'NumberCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'ReplaceValueNumeric',
                                                            margin: '0 80 0 10',
                                                            labelWidth: 60
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'ComboCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'DateCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'datefield',
                                                            itemId: 'ReplaceValueDate',
                                                            margin: '0 80 0 10',
                                                            labelWidth: 60
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    itemId: 'TextCont',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'ReplaceValueTextBox',
                                                            margin: '0 80 0 10',
                                                            width: 235
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 30,
                                            hidden: true,
                                            itemId: 'AdvanceFieldPanel',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'NumberPanel',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'checkboxfield',
                                                            itemId: 'PercentagecheckBox',
                                                            margin: '0 0 0 10',
                                                            fieldLabel: 'Percentage (%)'
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            flex: 1,
                                                            itemId: 'numberText',
                                                            margin: '0 80 0 20'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'DatePanel',
                                                    margin: '0 0 0 30',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            flex: 1,
                                                            itemId: 'AddDaysText',
                                                            margin: '0 80 0 10',
                                                            fieldLabel: 'Add Days',
                                                            labelWidth: 80
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: 26,
                                                    itemId: 'TextPanel',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            margins: '0 0 0 10',
                                                            itemId: 'TextText',
                                                            fieldLabel: 'Concate',
                                                            labelWidth: 45
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            itemId: 'AtFrontCheckBox',
                                                            margin: '0 30 0 30',
                                                            fieldLabel: 'At Front',
                                                            labelWidth: 40
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'SelectedGridPanel',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    itemId: 'SelectedFieldGrid',
                                                    margin: '10 10 10 10',
                                                    disableSelection: true,
                                                    store: 'SelectedValueJson',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            resizable: false,
                                                            dataIndex: 'FieldSelectedValue',
                                                            menuDisabled: true,
                                                            text: 'FieldSelectedValue',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            resizable: false,
                                                            dataIndex: 'ReplaceValue',
                                                            menuDisabled: true,
                                                            text: 'ReplaceValue',
                                                            flex: 1,
                                                            editor: {
                                                                xtype: 'textfield'
                                                            }
                                                        }
                                                    ],
                                                    plugins: [
                                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                                        })
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});