/*
 * File: app/view/AddCsvWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YBase.view.AddCsvWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.addCsvWindow',

    requires: [
        'Ext.container.Container',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    height: 440,
    itemId: 'AddCsvWindow',
    width: 400,
    resizable: false,
    layout: 'fit',
    title: 'AddCsvWindow',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'textareafield',
                                    itemId: 'csvFieldTextArea',
                                    margin: '10 5 0 5',
                                    fieldLabel: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 50,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '5 5 0 0',
                                    itemId: 'btnSave',
                                    iconCls: 'yig-save-s-w',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    margins: '5 0 0 5',
                                    itemId: 'btnCancel',
                                    icon: '',
                                    iconCls: 'yig-cancel-s-w',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});